### PR TITLE
feat: Add file browser for test generation

### PR DESCRIPTION
**Pull request by bjornpagen**
# Add File Selection UI for Test Generation

## Why

Right now, the shortest workflow relies on a GitHub PRs and diffs in order to generate test files for a repository. You open a PR, assign it to yourself, and the diff will appear in your shortest menu for you to click on and generate some test files.

However, it could be helpful for shortest to generate test files outside of the Pull Request workflow. This will benefit outside contributors (like me), since I can just generate new test files by selecting a repo, a branch, and some files.

This PR adds the feature for the user to navigate directly to a "File Select" tab, select a repo and branch, some files, and generate test files and commit them. It doesn't require the user to open a new PR.

Screenshot 2024-10-28 at 4 21 49 PM

## TODO
- Don't hardcode test file format config
- Test rewriting for failing tests

### CODE REVIEW

**Comment by slavingia** [comment]
Would be good to add a "why" to these PRs. Not intuitive why we need this

**Comment by m2rads** [comment]
Worth creating a cli for this? @slavingia  
npm package to support tests - cli to generate test and shortest web to provide testing infrastructure?

**Comment by slavingia** [comment]
Too many routes to using shortest imo. We're building for real companies, and real companies have proper CI and are building real features. This feels like a hack to make it easier to work on shortest but isn't relevant to real world uses

**Comment by slavingia** [comment]
I'm not saying it isn't useful, but ultimately developers are going to use this tool, and they're capable/it's probably faster to just write the tests as they're building the feature. Writing tests outside of the feature being built (or vise versa) seems unnecessary in a world where ppl are using shortest the right way (to write/maintain/run all their tests as they focus on building).

**Pull request closed without merging**
